### ISSUE TITLE
Restore of a backup

### ISSUE THREAD

**Issue by jtb0** [indiehosters/odoo#2]
Hello Pierre,

thank you very much for the nice odoo docker-repository.
The way a backup can be performed is documented. But can you tell me how
to restore?

Best regards,
Marcel

**Comment by pierreozoux** [comment]
Glad you like the package \o/

To restore, you'd need to copy back the folder to the place you want to restore it.
Once done, you should be able to restart it like usually.
If pg is complaining, you might need to restore pg as well.

then the idea is to "reset" and restore our dump.

as pg data are loaded from 'data', `docker-compose stop && mv data data_old`
Add this last line to docker-compose yml:

```
db:
  image: postgres
  volumes:
  - ./data:/var/lib/postgresql/data
  - ./data/dump.sql:/docker-entrypoint-initdb.d
```

And pg should start and restore your dump.

Let me know once tested if it works, and then could you do a PR to add the instructions?

Merci!
